### ISSUE TITLE
invalid import, invalid use of await.

### ISSUE THREAD

**Issue by JuanmaMenendez** [stylesuxx/proxy-source#1]
This project looks good but I was not able to run it.

I got several errors like:
invalid  import - from   use
invalid  await use
etc..

Please try to run it from scratch, just following your own instructions and you will see.

**Comment by mifi** [comment]
I think maybe this project doesn't support node.js (browser only?)

When i change the import to require and remove await i still get an error:
```
      var _ref2 = _asyncToGenerator( /*#__PURE__*/regeneratorRuntime.mark(function _callee2() {

ReferenceError: regeneratorRuntime is not defined
    at node_modules/proxy-source/lib/index.js:237:51
    at node_modules/proxy-source/lib/index.js:265:6

```
